---
name: Procedimientos
locale: es
type: learning
beta: false
teacher_info: ''
language: gobstones
id_format: '%05d'
order:
- 100
- 200
- 300
- 400
- 450
- 500
- 600
- 700
- 800
- 900
- 1000
- 1100
- 1101
